EFCoreTraning/Models/EFCoreDbContext.cs
using Microsoft.EntityFrameworkCore;


namespace EFCoreTraning.Models
{
    public class EFCoreDbContext : DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Note> Notes { get; set; }

        protected override void OnConfiguring( DbContextOptionsBuilder optionsBuilder )
        {
            optionsBuilder.UseMySql(
                       @"Server=127.0.0.1; Database=ef_test; User=root; Pwd=1234",
                        MySqlServerVersion.Parse("8.0.22-mysql") );
        }
    }
}

EFCoreTraning/Models/ErrorViewModel.cs
using System;

namespace EFCoreTraning.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty( RequestId );
    }
}

EFCoreTraning/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EFCoreTraning.Models
{
    public class Note
    {

        [Key]
        public int NoteNo { get; set; }

        [Required]
        public string NoteTitle { get; set; }

        [Required]
        public string NoteContents { get; set; }

        [Required]
        public int UserNo { get; set; }


        [ForeignKey("UserNo")]
        public virtual User User { get; set; }
    }
}

EFCoreTraning/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace EFCoreTraning.Models
{
    public class User
    {
        /// <summary>
        /// 사용자 번호
        /// </summary>
        [Key]
        public int UserNo { get; set; }

        [Required]
        public string UserName {  get; set; }

        [Required]
        public string UserId { get; set; }

        [Required]
        public string UserPassword {  get; set; }
    }
}

EFCoreTraning/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EFCoreTraning.ViewModels
{
    public class LoginViewModel
    {
        [Required( ErrorMessage = "사용자 ID를 입력하세요." )]
        public string UserId {  get; set; }

        [Required( ErrorMessage = "사용자 비밀번호를 입력하세요." )]
        public string UserPassword { get; set; }
    }
}

EFCoreTraning/Controllers/AccountController.cs
using EFCoreTraning.Models;
using EFCoreTraning.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFCoreTraning.Controllers
{
    public class AccountController : Controller
    {
        // GET: /controller/
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login( LoginViewModel model )
        {
            if ( ModelState.IsValid )
            {
                using ( var db = new EFCoreDbContext() )
                {
                    // Linq 메서드 체이닝
                    var user = db.Users.FirstOrDefault( 
                        u => u.UserId.Equals( model.UserId ) && 
                             u.UserPassword.Equals( model.UserPassword ) );
                    
                    if( null != user )
                    {
                        HttpContext.Session.SetInt32( "USER_LOGIN_KEY", user.UserNo );
                        return RedirectToAction( "LoginSuccess", "Home" );
                    }
                }

                ModelState.AddModelError( string.Empty, "사용자 ID 혹은 비밀번호가 올바르지 않습니다." );
            }

            return View( model );
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove( "USER_LOGIN_KEY" );
            return RedirectToAction( "Index", "Home" );

        }

        //public IActionResult Register()
        //{
        //    return View();
        //}


        [HttpPost]
        public IActionResult Register( User model )
        {
            if ( ModelState.IsValid )
            {
                using ( var db = new EFCoreDbContext() )
                {
                    db.Users.Add(model);
                    db.SaveChanges();
                }

                return RedirectToAction( "Index", "Home" );
            }

            return View(model);
        }
    }
}

EFCoreTraning/Controllers/HomeController.cs
using EFCoreTraning.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EFCoreTraning.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController( ILogger<HomeController> logger )
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult LoginSuccess()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache( Duration = 0, Location = ResponseCacheLocation.None, NoStore = true )]
        public IActionResult Error()
        {
            return View( new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier } );
        }
    }
}

EFCoreTraning/Controllers/NoteController.cs
using EFCoreTraning.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFCoreTraning.Controllers
{
    public class NoteController : Controller
    {
        public IActionResult Index()
        {
            using ( var db = new EFCoreDbContext() ) 
            {
                var list = db.Notes.ToList();
                return View( list );
            }
        }


        public IActionResult Add()
        {
            return View();
        }


        public IActionResult Edit()
        {
            return View();
        }

        public IActionResult Delete()
        {
            return View();
        }
    }
}

EFCoreTraning/Views/Home/LoginSuccess.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<h1>로그인 성공!</h1>

@{
}

EFCoreTraning/Views/Note/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

EFCoreTraning/Views/Note/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

EFCoreTraning/Views/Note/Index.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css" rel="stylesheet">
<script src="//code.jquery.com/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/latest/js/bootstrap.min.js"></script>

<table class='table table-bordered table-striped'>
    <thead>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
        </tr>
    </thead>

    <tbody>
        @foreach ( var note in Model )
        {
            <tr>
                <td>@note.NoteNo</td>
                <td>@note.NoteTile</td>
                <td>@note.UserNo</td>
            </tr>
        }
    </tbody>

</table>

<a class="btn btn-warning" asp-controller="Note" asp-action="Add">게시물 작성</a>

EFCoreTraning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData[ "Title" ] - EFCoreTraning</title>
    @using Microsoft.AspNetCore.Http;
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EFCoreTraning</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Note" asp-action="Index">게시판</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav navbar-right flex-grow-1">
                        @if ( Context.Session.GetInt32( "USER_LOGIN_KEY" ) == null )
                        {
                            <li> <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">로그인</a> </li>
                            <li> <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">회원가입</a> </li>
                        }
                        else
                        {
                            <li> <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">로그아웃</a> </li>
                        }
                    </ul>


                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EFCoreTraning - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>